### ISSUE TITLE
Publish the library to Arduino Library Manager

### ISSUE THREAD

**Issue by ofekp** [ofekp/TinyUPnP#16]
As suggested by @lucasromeiro in https://github.com/ofekp/TinyUPnP/issues/14:

> What do you think about simplifying it to make it more professional to get into Library Manager?
> I can help you!
> I already did that and I have a library there.
> I like to do this because like me, there are many other people who need ...
> The goal is to make it as simple as possible. And efficient!
> People love simple things that work well.
> If you accept, we can:

List of things to do:
1. - [x] Take all Prints in the serial and by a #define that enables them.
1. - [x] By return in this unique function so that the user knows when everything is OK or if he had some type of problem.
1. - [ ] Take as much dependence from other libraries as possible.
1. - [ ] Add these 3 functions to one (EasyDDNS.update (300000); tinyUPnP.updatePortMapping (600000, & connectWiFi); server.handleClient ();)
1. - [ ] Make a non-blocking code without delay if possible. For other functions can occur in parallel.
1. - [ ] Verify that the request parameters (GET and POST) are all present.
1. - [ ] Optimize memory.
1. - [ ] Test on other routers

**Comment by ofekp** [comment]
@lucasromeiro

1. All my prints inside the TinyUPnP (excluding the example .ino code) are surrounded by a check of a defined flag `if (IS_DEBUG) { ... }` the flag `IS_DEBUG` is founf in the [`TinyUPnP.h`](https://github.com/ofekp/TinyUPnP/blob/master/src/TinyUPnP.h#L16) file. Can we mark item 1 as done?

2. ESP8266Ping? Anything else? You mean anything inside the example .ino file is OK to keep such as the EasyDDNS?

3. How do you want to add these 3 methods to 1? Each of them are from different libraries.

4. Since I do make HTTP requests, how can make it faster? Any suggestions?

5. what do you mean by that please?

6. I will make `updatePortMapping` return a boolean indicating that the rule addition was successful.

Thanks for the help!

**Comment by lucasromeiro** [comment]
1. Perfect, we mark item 1 as done!

2. For me: remove ESP8266Ping and EasyDDNS if possible. EasyDDNS is necessary to work? In .ino file we can do a simple examples. I can help you with this! For example, i can send a http page without dependences, it is simple. And develop others examples.

3. EasyDDNS.update (300000); is really necessary? The server.handleClient (); and replace to a simple function, i can do a sample for you! And use a simple one function to handle the UPnP, example: TinyUPnP.handle(); (the function return the state). The other parameters we can chance with other function, example: TinyUPnP.config(a,b,c,d,e,f,g);

4. We can put all POST and GET structure in the same line and FLUSH command in the end!
Example(That's what I wanted to talk about in item 5):
  client.print(String("POST ") + upload +
               host_content +
               "User-Agent: ESP8266/Arduino_Dropbox_Manager_"+(String)ver+"\r\n" +
               (String)Aut_Bearer + (String)_token +"\r\n" +
               _accept +
               "Dropbox-API-Arg: {\"path\": \"" + address + "\",\"mode\": \"" + _mode + "\",\"autorename\": true,\"mute\": false}\r\n" +
               content_type_octet +
               "Content-Length: " + data.length() + "\r\n\r\n" +
               data
               );
Probably is more fast... We can test and improve.
But, one important thing is to make a non-blocking code. We can not use delay.
There are several ways to do this ...
One of them is to use millis () which gives you a count if milliseconds since the MCU was turned on or reset, this number always grows and only resolves after approximately 50 days if I am not mistaken. Then you save the current millis () in a variable uint32_t to know when it started and compare it with millis (), so you will know how much time has passed and do not need to do a delay for all the code. If you do not understand, tell me that I can set an example for you.

5. I explained and sent a sample post in item 4, but we can search to know if we can for more parameters to meet the most demanding routers.

6. Can door addition only be successful or unsuccessful? Do you have any other conditions? For example, busy router. You could separate these errors for the user to know that if he receives 1 the rule was added, if he receives 2 the router is busy and he can try again then if he receives 3 the rule was not rejected by the router and it will not be possible to do , then the user would not have to keep trying in this case. It's an option ... Think about it a little.

**Comment by lucasromeiro** [comment]
If you need, i can help you.

**Comment by ofekp** [comment]
Please check the branch `publishPackage` I have create a return enum for `updatePortMapping` method.
Regarding the `ESP8266Ping` is it really required to remove this? I guess a lot of packages are depending upon other Library packages and I will have to implement this myself if I remove it which seems redundant. Do you have other suggestion as to how to do it? EasyDDNS is only in the example, I can make another example without it, but I want to keep this one too since this is a very common use case.

**Comment by lucasromeiro** [comment]
I saw the change in the updatePortMapping function. Very good!

My opinion is that it should remove ESP8266Ping yes.
Because it's more of a dependency for your library to work.
If you want to succeed, the library has to be as simple as possible.
Dependencies drive away users with less knowledge.

How about your opinion on EasyDDNS agree!
You're right about that.
But, create simple examples. Not all users understand as we do.
Many just want to download and watch work without needing much effort.

Important not to have too much memory. You already do a great job using F ()!

Most important of all is that it works on the largest possible number of routers and reliably, so that the users themselves can make it known to you.

Simplicity and efficiency. This is the secret.

**Comment by lucasromeiro** [comment]
To build the library in Arduino formats, look at these websites. I used them as a guide to mine. 
 it's all up to the standards and made changes to the library, let me know what to do to include it in the library manager. It's simple!

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

https://www.embedded.fm/blog/2017/8/12/dont-use-arduino-for-professional-work?format=amp

https://www.teachmemicro.com/create-arduino-library/

**Comment by amiraraboy** [comment]
this library is perfect but use too much memory
please optimize that

**Comment by amiraraboy** [comment]
when I use this library in my project dynamic memory used go from 61% to 86% and scketch cant run
when I replase UDP_TX_PACKET_MAX_SIZE with 1000 every thing is ok
is it possible to change that with minimum size?

**Comment by ofekp** [comment]
@lucasromeiro - Will attend to these in a few days. Thank you so much for the help :)

@amiraraboy - I am converned about this affecting the usage for different routers, I will try to see if it is indeed not an issue, and will reduce the number. What usage percentage were you getting for 1000 please?

**Comment by amiraraboy** [comment]
@ofekp I get 65% and it's ok
I use OTA update and the size of sketch is 51% now that it warn low memory for updating
if you remove arduino.ping is it possible the size of sketch be lower?
thanks

**Comment by lucasromeiro** [comment]
Very important that there is an optimization of memory usage.
It is important to check if there is no memory leak.
This type of optimization is important so users can use without compromising the main purpose of their projects.
Removing dependencies will also help you get your program up and running, even if the third-party library changes or ceases to exist.

**Comment by amiraraboy** [comment]
I remove esp8266ping and all Serial.print from library for reducing sketch size
library do portmaping very well but cant from while
 // while (!portMappingAdded) {
    portMappingAdded = tinyUPnP.addPortMapping();
    //myserialPrintln("");
  //  if (!portMappingAdded) {
      // for debugging, you can see this in your router too under forwarding or UPnP
      //tinyUPnP.printAllPortMappings();
      //myserialPrintln(F("failed"));
    //  delay(30000);  // 30 seconds before trying again
   // }
  //}

so I comment that temperorely

**Comment by amiraraboy** [comment]
> 
> 
> I remove esp8266ping and all Serial.print from library for reducing sketch size
> library do portmaping very well but cant exit from while
> // while (!portMappingAdded) {
> portMappingAdded = tinyUPnP.addPortMapping();
> //myserialPrintln("");
> // if (!portMappingAdded) {
> // for debugging, you can see this in your router too under forwarding or UPnP
> //tinyUPnP.printAllPortMappings();
> //myserialPrintln(F("failed"));
> // delay(30000); // 30 seconds before trying again
> // }
> //}
> 
> so I comment that temporarely

port mapping done but print "This was printed because adding the required port mapping failed
" and stay in while

**Comment by amiraraboy** [comment]
> 

> @amiraraboy is it possible that the loop seems infinite due to the large delay I placed there (`delay(30000)`)?
it cant exit from loop because of this message:
"This was printed because adding the required port mapping failed
" and stay in while

**Comment by amiraraboy** [comment]
> 
> 
>     * @lucasromeiro I attended to [#16 (comment)](https://github.com/ofekp/TinyUPnP/issues/16#issuecomment-425655107) - ESP8266Ping is removed entirely in the branch `publishPackage`.
> 
>     * @amiraraboy Regarding UDP_TX_PACKET_MAX_SIZE, I made a change that will support reducing this buffer size (`publishPackage` branch). However, I will need to check this thoroughly (when a new FTDI arrives in the mail, soon I hope).
>       This gives me the following memory state for an ESP8266:
> 
> 
> ```
> Sketch uses 313536 bytes (62%) of program storage space. Maximum is 499696 bytes.
> Global variables use 41320 bytes (50%) of dynamic memory, leaving 40600 bytes for local variables. Maximum is 81920 bytes.
> ```
> 
> @araboy, @amiraraboy The idea behind that setup loop is that the server will be ready for use as soon as it loads up. I assumed there is no point in loading the server if you cannot get the port mapping to succeed.
> Not sure moving this to loop() is the best thing to do.
> @amiraraboy is it possible that the loop seems infinite due to the large delay I placed there (`delay(30000)`)?

it cant exit from loop because of this message:
"This was printed because adding the required port mapping failed
" and stay in while

**Comment by ofekp** [comment]
@amiraraboy As I said, there is a 30 sec delay after that message. Have you tried waiting more than 30 seconds?
I can lower this delay too and then the loop will try to connect again. Does that work for you?

**Comment by ofekp** [comment]
Branch `publishPackage` is functioning well after a few bug fixes.
It can be uploaded to devices now (mind you the few extra debug logs).
Will appreciate if anyone can install and verify it (as I am doing now).

**Comment by ofekp** [comment]
Thanks @Tristan8686
Please open a different issue and attach a full log (as a text file like .txt) and we will start from there.

**Comment by lucasromeiro** [comment]
Hello, any progress updates to launch in Library Manager?

**Comment by ofekp** [comment]
@Tristan8686 Any progress?
@lucasromeiro Thanks for coming back. Will do so in the next few days.

**Comment by lucasromeiro** [comment]
Nice! Finish the library? Congratulations!

**Comment by ofekp** [comment]
Thank you everyone for the support, especially @lucasromeiro who encouraged me to publish this package!
I will continue to support this package to make it more resilient in the future.
😄
